"use client";

import { useState } from "react";

import type { Supplier, SupplierInput } from "../types/supplier.types";

export function SupplierFormDialog({ initial, onClose, onSubmit }: { initial?: Supplier; onClose: () => void; onSubmit: (input: SupplierInput) => Promise<void> }) {
  const [values, setValues] = useState({ name: initial?.name ?? "", taxId: initial?.taxId ?? "", contactName: initial?.contactName ?? "", phone: initial?.phone ?? "", email: initial?.email ?? "", address: initial?.address ?? "", notes: initial?.notes ?? "" });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  function field(name: keyof typeof values) { return { value: values[name], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValues((current) => ({ ...current, [name]: event.target.value })) }; }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError(null); setSaving(true);
    try { await onSubmit(values); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar."); setSaving(false); }
  }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-6"><section aria-labelledby="supplier-form-title" aria-modal="true" className="max-h-[96vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl" role="dialog"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-200 bg-white/95 p-5 sm:px-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Directorio de abastecimiento</p><h2 className="mt-1 text-2xl font-bold" id="supplier-form-title">{initial ? "Editar proveedor" : "Nuevo proveedor"}</h2></div><button aria-label="Cerrar" className="size-10 rounded-xl border border-slate-200 text-2xl" onClick={onClose} type="button">×</button></div><form className="space-y-5 p-5 sm:p-7" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Nombre *<input {...field("name")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={160} required /></label><label className="text-sm font-semibold">RUC / Tax ID<input {...field("taxId")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={40} /></label><label className="text-sm font-semibold">Contacto<input {...field("contactName")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={120} /></label><label className="text-sm font-semibold">Teléfono<input {...field("phone")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={40} /></label><label className="text-sm font-semibold">Email<input {...field("email")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={160} type="email" /></label><label className="text-sm font-semibold sm:col-span-2">Dirección<input {...field("address")} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={240} /></label><label className="text-sm font-semibold sm:col-span-2">Notas<textarea {...field("notes")} className="mt-2 min-h-24 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal" maxLength={500} /></label></div>{error ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p> : null}<div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold" disabled={saving} onClick={onClose} type="button">Cancelar</button><button className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? "Guardando..." : "Guardar proveedor"}</button></div></form></section></div>;
}
