"use client";

import type { UserRole } from "@/features/auth";
import { SalePaymentProofSection } from "@/features/payment-proofs";

import type { Sale } from "../types/sale.types";
import { formatMoney, PAYMENT_METHOD_LABELS } from "../utils/sale-utils";

interface SaleDetailDialogProps { actorUid: string; agentLabel: string; onClose: () => void; role: UserRole; sale: Sale; }

export function SaleDetailDialog({ actorUid, agentLabel, onClose, role, sale }: SaleDetailDialogProps) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/60 backdrop-blur-sm sm:items-center sm:p-6"><section aria-labelledby="sale-detail-title" aria-modal="true" className="max-h-[95vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl" role="dialog">
    <div className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-slate-200 bg-white/95 px-5 py-5 backdrop-blur sm:px-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Detalle de venta</p><h2 className="mt-1 text-2xl font-bold text-slate-950" id="sale-detail-title">{sale.number}</h2></div><button aria-label="Cerrar detalle" className="flex size-10 items-center justify-center rounded-xl border border-slate-200 text-2xl text-slate-600" onClick={onClose} type="button">×</button></div>
    <div className="space-y-6 p-5 sm:p-7"><div className="grid gap-4 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-xs text-slate-500">Estado</p><p className="mt-1 text-sm font-semibold text-emerald-800">{sale.status === "completed" ? "Completada" : "Anulada"}</p></div><div><p className="text-xs text-slate-500">Fecha</p><p className="mt-1 text-sm font-semibold text-slate-900">{new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(sale.createdAt.toDate())}</p></div><div><p className="text-xs text-slate-500">Cliente</p><p className="mt-1 text-sm font-semibold text-slate-900">{sale.clientSnapshot.name}</p><p className="text-xs text-slate-500">{sale.clientSnapshot.documentType} {sale.clientSnapshot.documentNumber}</p></div><div><p className="text-xs text-slate-500">Agente</p><p className="mt-1 text-sm font-semibold text-slate-900">{agentLabel}</p></div><div><p className="text-xs text-slate-500">Pago</p><p className="mt-1 text-sm font-semibold text-slate-900">{PAYMENT_METHOD_LABELS[sale.paymentMethod]}</p><p className="text-xs text-slate-500">{sale.paymentReference || "Sin referencia"}</p></div></div>
      <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full divide-y divide-slate-200 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Producto</th><th className="px-4 py-3">Cantidad</th><th className="px-4 py-3">Precio</th><th className="px-4 py-3">Descuento</th><th className="px-4 py-3">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{sale.items.map((item) => <tr key={item.productId}><td className="px-4 py-4"><p className="font-semibold text-slate-950">{item.name}</p><p className="font-mono text-xs text-slate-500">{item.sku}</p></td><td className="px-4 py-4">{item.quantity}</td><td className="px-4 py-4">{formatMoney(item.unitPrice)}</td><td className="px-4 py-4">{formatMoney(item.discountAmount)}</td><td className="px-4 py-4 font-bold">{formatMoney(item.lineTotal)}</td></tr>)}</tbody></table></div>
      <div className="ml-auto grid max-w-md gap-2 rounded-2xl border border-slate-200 p-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><strong>{formatMoney(sale.subtotal)}</strong></div><div className="flex justify-between text-red-700"><span>Descuento total</span><strong>− {formatMoney(sale.totalDiscount)}</strong></div><div className="flex justify-between border-t border-slate-200 pt-2 text-lg"><span className="font-bold">Total</span><strong>{formatMoney(sale.total)}</strong></div></div>
      <SalePaymentProofSection actorUid={actorUid} role={role} sale={sale} />
      {sale.notes ? <div><p className="text-xs font-semibold uppercase text-slate-500">Notas</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{sale.notes}</p></div> : null}
    </div>
  </section></div>;
}
